apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:  
  selector:
      app: frontend-py
  ports:
   - name: http
     protocol: TCP
     targetPort: 80
     port: 80
  type: ClusterIP
  
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend-py
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-py
  template:
    metadata:
      labels:
        app: frontend-py 
    spec:
      containers:
        - name: frontend-py
          image: ajmalk/pebble:frontend-0
          ports:
           - containerPort: 80
          resources: {}
            